on: pull_request

jobs:
  build_arm:
    runs-on: ubuntu-18.04
    name: Build on ${{ matrix.arch }}

    strategy:
      matrix:
        include:
          - arch: armv6
            distro: alpine_latest
          - arch: armv7
            distro: ubuntu18.04
          - arch: aarch64
            distro: ubuntu18.04
          - arch: s390x
            distro: ubuntu18.04
          - arch: ppc64le
            distro: ubuntu18.04

    steps:
      - uses: actions/checkout@v2.1.0
        with:
          submodules: true
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Build and deploy package
        id: build-and-deploy
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          # Not required, but speeds up builds
          githubToken: ${{ github.token }}

          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"

          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"

          # The shell to run commands with in the container
          shell: /bin/sh

          # Install some dependencies in the container. This speeds up builds if
          # you are also using githubToken. Any dependencies installed here will
          # be part of the container image that gets cached, so subsequent
          # builds don't have to re-install them. The image layer is cached
          # publicly in your project's package repository, so it is vital that
          # no secrets are present in the container state or logs.
          install: |
            case "${{ matrix.distro }}" in
              ubuntu*|jessie|stretch|buster|bullseye)
                apt-get update -q -y
                apt-get install -q -y git libssl-dev openssl wget
                wget https://www.python.org/ftp/python/3.7.12/Python-3.7.12.tgz
                tar xzvf Python-3.7.12.tgz
                cd Python-3.7.12
                ./configure
                make
                sudo make install
                ln -fs ./Python /usr/bin/python3
                cd ..
                ;;
              alpine*)
                apk update
                apk add git gcc
                apk add --no-cache python3 py3-pip
                ;;
            esac

          run: |
            python3 -m pip install --upgrade pip
            pip install poetry
            poetry install

  build_x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Python 3.7.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Build package
        run: |
          poetry build